

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3005
    command: npm run dev
